<?php
// Design Tokens — auto-generated inclusion for PHP pages
// This sets CSS custom properties from the tokens.css file
// Include this in PHP pages that need design token access

$tokens = [
    'primary'           => '#5B1EBC',
    'primaryLight'      => '#7B3FE4',
    'primaryDark'       => '#3D0F8A',
    'secondary'         => '#0F6CBD',
    'secondaryLight'    => '#1E88E5',
    'accent'            => '#F57C00',
    'accentLight'       => '#FF9800',
    'success'           => '#22c55e',
    'warning'           => '#f59e0b',
    'danger'            => '#ef4444',
    'info'              => '#0F6CBD',
    'bgDark'            => '#0A0833',
    'bgDarker'          => '#050520',
    'bgLight'           => '#F8F9FE',
    'bgPanel'           => '#FFFFFF',
    'bgSubtle'          => '#F0EBFF',
    'colorTextDark'     => '#0F172A',
    'colorTextLight'    => '#64748B',
    'colorTextMuted'    => '#94A3B8',
    'colorOnDark'       => '#F8FAFF',
    'colorOnLight'      => '#0F172A',
    'borderDefault'     => '#E2E8F0',
    'borderSoft'        => '#E2E8F0',
    'borderAccent'      => '#C4A9FF',
    'shadowSm'          => '0 1px 2px rgba(0, 0, 0, 0.05)',
    'shadowMd'          => '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
    'shadowLg'          => '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
    'shadowCard'        => '0 4px 16px rgba(0, 0, 0, 0.08)',
    'radiusSm'          => '6px',
    'radiusMd'          => '10px',
    'radiusLg'          => '16px',
    'radiusFull'        => '9999px',
    'space1'            => '4px',
    'space2'            => '8px',
    'space3'            => '12px',
    'space4'            => '16px',
    'space5'            => '20px',
    'space6'            => '24px',
    'space8'            => '32px',
    'fontXs'            => '0.65rem',
    'fontSm'            => '0.75rem',
    'fontBase'          => '0.875rem',
    'fontMd'            => '1rem',
    'fontLg'            => '1.25rem',
    'fontXl'            => '1.5rem',
    'font2xl'           => '2rem',
    'font3xl'           => '2.25rem',
    'font4xl'           => '3rem',
    'zNav'              => '1000',
    'zSticky'           => '50',
    'zCard'             => '10',
    'zTooltip'          => '100',
    'zModal'            => '1000',
];
?>